### PR TITLE
Use Tailwind for styling instead of bootstrap

### LINKED ISSUE #1: Drop any dependency on Bootstrap and instead render our Scrive Lib.UI components! 🆙

### PR DESCRIPTION
**Pull request by kutyel**
Fixes #1

### CODE REVIEW

**Comment by kutyel** [comment]
@kraklin could you work a little bit more on this PR before merging? If you have the time, if not I can take it up eventually. 🙏🏻

**Comment by kraklin** [comment]
@kutyel feel free to pick this up - I really took it up just to prove you that it is not the months of a work, but rather few days for us to get rid of bootstrap here :D

**Comment by kraklin** [comment]
I just realised that we might have a problem with using this with tailwind. Our tailwind setup is built in a way that we generate the CSS for apps based on the actual classes used in the project. But with the styles being defined here in the package instead, we might not have those classes used there in the resulting CSS as the generation script doesn't have a way on how to scrape those from package.

I think that we really should move the rendering to the app instead of this library to be in charge of rendering form items.

**Comment by kutyel** [comment]
> I just realised that we might have a problem with using this with tailwind. Our tailwind setup is built in a way that we generate the CSS for apps based on the actual classes used in the project. But with the styles being defined here in the package instead, we might not have those classes used there in the resulting CSS as the generation script doesn't have a way on how to scrape those from package.
> 
> I think that we really should move the rendering to the app instead of this library to be in charge of rendering form items.

Can we somehow make an exception for flow-ui then and just load all tailwindcss classes as we did with bootstrap? 🤔

**Comment by kraklin** [comment]
> > I just realised that we might have a problem with using this with tailwind. Our tailwind setup is built in a way that we generate the CSS for apps based on the actual classes used in the project. But with the styles being defined here in the package instead, we might not have those classes used there in the resulting CSS as the generation script doesn't have a way on how to scrape those from package.
> > I think that we really should move the rendering to the app instead of this library to be in charge of rendering form items.
> 
> Can we somehow make an exception for flow-ui then and just load all tailwindcss classes as we did with bootstrap? 🤔

I think it will not be a good idea, the CSS will be quite long. And when you load the CDN version, it will lack the scrive specific styles. IMHO the correct way forward will be to rewrite this using Theme module and define those look and feel classes in the flow-ui app.

**Comment by kraklin** [comment]
@kutyel I have rewrote this library to have Theme - a record, that defines styles. So now we can have those style definitions in the app, rather than in the package. I kept the `Theme.default` to be the same as before - bootstrap 4. But take a look at example/Main.elm to see the Tailwind version defined there.

What has left for now is the tests need to be fixed.

**Pull request merged**
